notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: qj1C85av+1QhAn5RYy8s9bqQIiE/B4ZkAL5v1rzDXDLlWtyLFUbN+E+aHJqv6L5L43MOK8BdV7UdzFnwu3anrUjUSjI/d9BD3fqU+vD5qLAif7ec/iR2v7W3osRBGXZWvQx/8tc8UGO200rWTrLTteD00iMubAyKajJnpCb6Orw9k1XG2j7BB68el9JdLhTKJIl0fJC1mD7bTcUTmBHqovpm/vreb/sh2XDxOHkYRL5vjgVEX0DoMr9IOxm3gbTiCxBi7+ZfXk5XSYVUeESbbwyD5q329/Yg0NVTVQwBsIgn8KTr4iNqGf08/3lUotUS9aHOjXnAyQYXtqBh3IqMMc3kgdpLXkHmz6kZqXqSe/QqYZr0OUJQeLWf6pXM+2UTW6rgSkNw6b+qlO41xifzKZhH8Ki4QHjA4OlwXHN5VU9ZjSsRNXOZJimu/mYWnAxz6mE3u5lERBba4oqd1bHDxKnv0j2Fx3vhMdx9Dlcu7JrqvryA552EnRC6EIHsMEp9tiSYwhakaoBngAC1/2cU9hnBB7x575WaMBMBz4Pw5dDg6Z2Yj3ilcxphQiHjaRXrve1whABZcOmlvzpuxHPCf4lk5cVPQWbmw4EJ8QxkCGNOSCwZluKW1lDWPtuA9k2MlHNgC6ruLosesj51kifFZT3rF8vVd5W+RN3/cr0pH+4=
  api_key:
    secure: I5Wv9daPnfUh6caM9I0MFJAZk6lvmTqHgY02Reeti1+kXHGe7cAdX3VkEa86VVj99MzwAiT7nlRwRYvZvl2vdfxYuITHefC8VyUKIMMnWm2Xai+CxUqxKP3GLj4rlyQY9m+TQh0ZwnULBuUyz7NxzlZzSLAkTp/79SfewdMB26eexITo5Vbs1SAhXlPIQzNTB5cF5FUtt4tKLMCGfGhisgdJtaPl5kz3RHUYzXPzNK3xayrAABQbiXATWHq0Bqo6lqolGW87ZjpvdNOsZPbZ1WhdZW+NrDznNjqFab+iL08fRtPRAqR4dCpa+QtjU69zXXmEyGiruYgmPNiEQIde7kf/smFbuK7xEoOE9ub8Kh12BBy1H0k3JJ0+8cpbbClxOWWoZNei4trLmLXXOIoVl/RwEp2XEzT+ICe2JLhOEyrHwCjyZon/4VocPdycBUoC33w6lXSn4E5bJCapUdOo5+SxfhmwVKGggWgDyCzQ+WlnrlZ9MSGI8LK65M9NMvYEFFEhsl2h0viWbNIk++2um1gQIS8CLPObVyhh9m84DyvTIG/WinHVgE0tdVX4UoLBJfyRJI9QTSryuV79Cld4uacxfOvG6tmQWFiHKJ0Zozp7X+fShIjQE6WG5EmtfkG9FO3Z0pQ7SNHr0gSd7rPH9VZm5ug5WENNPPClVG42bBE=
  on:
    tags: true
